site_name: "cedar-python"
site_description: "Python bindings for cedar policy language."
site_url: "https://charbonnierg.github.io/cedar-python"
repo_url: "https://github.com/charbonnierg/cedar-python"
repo_name: "charbonnierg/cedar-python"
copyright: Copyright &copy; 2025 Guillaume Charbonnier
edit_uri: edit/main/docs/

theme:
  name: "material"
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: python
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "¤"

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          paths: [python]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            filters: ["!^_"]
            heading_level: 3
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            allow_inspection: true
            find_stubs_package: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/charbonnierg
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cedar-python/
